# src/saving/pdf_builder.py
import re
from html import escape
from typing import List
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.colors import Color, HexColor
from reportlab.pdfgen.canvas import Canvas

from .fonts import (
    register_cjk_fonts,
    register_emoji_font,
    contains_cjk,
    CJK_FONT_NAME_SONG,
    CJK_FONT_NAME_SONG_2,
    NOTO_FONT_NAME_SERIF,
)
from .markdown import markdown_inline_to_html


def _add_watermark(canvas: Canvas, doc) -> None:
    """
    Draws a very light watermark on each page.
    """
    canvas.saveState()

    watermark_text = "Generated by AI Agent Researcher"
    color = Color(0.5, 0.7, 0.8, alpha=0.08)
    canvas.setFillColor(color)
    canvas.setFont("Courier-Bold", 40)

    canvas.translate(300, 400)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, watermark_text)

    canvas.restoreState()


def build_pdf_document(query: str, result_text: str, pdf_path: str) -> None:
    """
    Build a PDF with 4 styles (Title, H2, H3, Body) and simple markdown support.
    """
    full_text = f"{query}\n{result_text}"
    uses_cjk = contains_cjk(full_text)

    # Register TTF fonts (CJK + Noto) for all docs
    register_cjk_fonts()

    # If any emoji present, register emoji font
    #if re.search(r"[\U0001F300-\U0001FAFF]", full_text):
    register_emoji_font()

    # --- base doc (this must ALWAYS run, emoji or not) ---
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=60,
        rightMargin=60,
        topMargin=60,
        bottomMargin=60,
    )

    styles = getSampleStyleSheet()

    # ------- COLORS (tweak if you like) -------
    title_color = HexColor("#1F4E79")  # deep blue
    h2_bg = HexColor("#EAF2F8")        # very light blue
    h2_color = HexColor("#154360")
    h3_color = HexColor("#2E86C1")
    body_color = HexColor("#333333")

    if uses_cjk:
        body_style = ParagraphStyle(
            "BodyCJK",
            parent=styles["Normal"],
            fontName=CJK_FONT_NAME_SONG_2,
            fontSize=11.5,
            leading=17,
            textColor=body_color,
            spaceAfter=10,
        )
        title_style = ParagraphStyle(
            "TitleCJK",
            parent=styles["Heading1"],
            fontName=NOTO_FONT_NAME_SERIF,
            fontSize=22,
            leading=26,
            textColor=title_color,
            spaceAfter=12,
            alignment=1,  # center
        )
        heading2_style = ParagraphStyle(
            "Heading2CJK",
            parent=styles["Heading2"],
            fontName=CJK_FONT_NAME_SONG_2,
            fontSize=16,
            leading=20,
            textColor=h2_color,
            backColor=h2_bg,
            spaceBefore=14,
            spaceAfter=8,
            leftIndent=4,
            rightIndent=4,
        )
        heading3_style = ParagraphStyle(
            "Heading3CJK",
            parent=styles["Heading3"],
            fontName=CJK_FONT_NAME_SONG,
            fontSize=14,
            leading=18,
            textColor=h3_color,
            spaceBefore=10,
            spaceAfter=4,
        )
    else:
        body_style = ParagraphStyle(
            "BodyLatin",
            parent=styles["Normal"],
            fontName="Times-Roman",
            fontSize=11.5,
            leading=17,
            textColor=body_color,
            spaceAfter=10,
        )
        title_style = ParagraphStyle(
            "TitleLatin",
            parent=styles["Heading1"],
            fontName="Times-Bold",
            fontSize=20,
            leading=26,
            textColor=title_color,
            spaceAfter=12,
            alignment=1,
        )
        heading2_style = ParagraphStyle(
            "Heading2Latin",
            parent=styles["Heading2"],
            fontName="Times-Bold",
            fontSize=15,
            leading=20,
            textColor=h2_color,
            backColor=h2_bg,
            spaceBefore=14,
            spaceAfter=8,
            leftIndent=4,
            rightIndent=4,
        )
        heading3_style = ParagraphStyle(
            "Heading3Latin",
            parent=styles["Heading3"],
            fontName="Times-Bold",
            fontSize=13,
            leading=18,
            textColor=h3_color,
            spaceBefore=10,
            spaceAfter=4,
        )

    story: list = []

    # -------- Title block ----------
    title_text = query.strip() or "Research Result"
    story.append(
        Paragraph(
            markdown_inline_to_html(f"📊 {escape(title_text)}", uses_cjk),
            title_style,
        )
    )
    story.append(Spacer(1, 6))

    subtitle = (
        "工具评估与架构分析指南"
        if uses_cjk
        else "Tool Evaluation & Architecture Analysis Guide"
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontName=body_style.fontName,
        fontSize=11,
        leading=14,
        textColor=HexColor("#555555"),
        alignment=1,
        spaceAfter=16,
    )
    story.append(Paragraph(escape(subtitle), subtitle_style))

    # -------- Body: parse headings & paragraphs ----------
    for raw_line in result_text.splitlines():
        line = raw_line.rstrip("\n")

        if not line.strip():
            story.append(Spacer(1, 4))
            continue

        # H2: lines starting with "## "
        if line.startswith("## "):
            content = line[3:].strip()
            story.append(
                Paragraph(
                    markdown_inline_to_html(content, uses_cjk),
                    heading2_style,
                )
            )
            continue

        # H3: lines starting with "### "
        if line.startswith("### "):
            content = line[4:].strip()
            story.append(
                Paragraph(
                    markdown_inline_to_html(content, uses_cjk),
                    heading3_style,
                )
            )
            continue

        # Normal body
        story.append(
            Paragraph(
                markdown_inline_to_html(line, uses_cjk),
                body_style,
            )
        )

    doc.build(
        story,
        onFirstPage=_add_watermark,
        onLaterPages=_add_watermark,
    )
