# src/saving/pdf_builder.py
import re
from typing import List
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.colors import Color
from reportlab.pdfgen.canvas import Canvas

from .fonts import (
    register_cjk_fonts,
    register_emoji_font,
    contains_cjk,
    CJK_FONT_NAME_SONG,
    CJK_FONT_NAME_SONG_2,
    NOTO_FONT_NAME_SERIF,
)
from .markdown import markdown_inline_to_html


def _add_watermark(canvas: Canvas, doc) -> None:
    """
    Draws a very light watermark on each page.
    """
    canvas.saveState()

    watermark_text = "Generated by AI Agent Researcher"
    color = Color(0.5, 0.7, 0.8, alpha=0.08)
    canvas.setFillColor(color)
    canvas.setFont("Courier-Bold", 40)

    canvas.translate(300, 400)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, watermark_text)

    canvas.restoreState()


def build_pdf_document(query: str, result_text: str, pdf_path: str) -> None:
    """
    Build a PDF with 4 styles (Title, H2, H3, Body) and simple markdown support.
    """
    full_text = f"{query}\n{result_text}"
    uses_cjk = contains_cjk(full_text)

    # Register TTF fonts (CJK + Noto) for all docs
    register_cjk_fonts()

    # If any emoji present, register emoji font
    if re.search(r"[\U0001F300-\U0001FAFF]", full_text):
        register_emoji_font()

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=60,
        rightMargin=60,
        topMargin=50,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()

    if uses_cjk:
        # ---- Chinese styles ----
        body_style = ParagraphStyle(
            "BodyCJK",
            parent=styles["Normal"],
            fontName=CJK_FONT_NAME_SONG_2,
            fontSize=12,
            leading=18,
            spaceAfter=12,
            alignment=0,
            allowBold=True,
        )
        title_style = ParagraphStyle(
            "TitleCJK",
            parent=styles["Heading1"],
            fontName=NOTO_FONT_NAME_SERIF,
            fontSize=22,
            leading=26,
            spaceAfter=20,
            spaceBefore=0,
            alignment=1,
            allowBold=True,
        )
        heading2_style = ParagraphStyle(
            "Heading2CJK",
            parent=styles["Heading2"],
            fontName=CJK_FONT_NAME_SONG_2,
            fontSize=16,
            leading=20,
            spaceBefore=16,
            spaceAfter=10,
            textColor="#2c3e50",
            allowBold=True,
        )
        heading3_style = ParagraphStyle(
            "Heading3CJK",
            parent=styles["Heading3"],
            fontName=CJK_FONT_NAME_SONG,
            fontSize=14,
            leading=18,
            spaceBefore=12,
            spaceAfter=8,
            textColor="#34495e",
            allowBold=True,
        )
    else:
        # ---- Latin styles (Noto serif) ----
        body_style = ParagraphStyle(
            "BodyLatin",
            parent=styles["Normal"],
            fontName=NOTO_FONT_NAME_SERIF,
            fontSize=12,
            leading=18,
            spaceAfter=12,
            alignment=0,
            allowBold=True,
        )
        title_style = ParagraphStyle(
            "TitleLatin",
            parent=styles["Heading1"],
            fontName=NOTO_FONT_NAME_SERIF,
            fontSize=18,
            leading=24,
            spaceAfter=16,
            spaceBefore=0,
            alignment=1,
            allowBold=True,
        )
        heading2_style = ParagraphStyle(
            "Heading2Latin",
            parent=styles["Heading2"],
            fontName=NOTO_FONT_NAME_SERIF,
            fontSize=14,
            leading=20,
            spaceBefore=10,
            spaceAfter=10,
            textColor="#2c3e50",
            allowBold=True,
        )
        heading3_style = ParagraphStyle(
            "Heading3Latin",
            parent=styles["Heading3"],
            fontName=NOTO_FONT_NAME_SERIF,
            fontSize=12,
            leading=18,
            spaceBefore=8,
            spaceAfter=8,
            textColor="#34495e",
            allowBold=True,
        )

    story: List = []

    # Title
    story.append(Paragraph(markdown_inline_to_html(query, uses_cjk), title_style))
    story.append(Spacer(1, 12))

    # Body
    for raw_line in result_text.splitlines():
        line = raw_line.rstrip("\n")

        # Extra spaces after full-width colon `：`
        line = re.sub(r"：(?=\S)", "：   ", line)

        if not line.strip():
            story.append(Spacer(1, 6))
            continue

        if line.startswith("## "):
            content = line[3:].strip()
            story.append(
                Paragraph(
                    markdown_inline_to_html(content, uses_cjk),
                    heading2_style,
                )
            )
            continue

        if line.startswith("### "):
            content = line[4:].strip()
            story.append(
                Paragraph(
                    markdown_inline_to_html(content, uses_cjk),
                    heading3_style,
                )
            )
            continue

        story.append(
            Paragraph(
                markdown_inline_to_html(line, uses_cjk),
                body_style,
            )
        )

    doc.build(
        story,
        onFirstPage=_add_watermark,
        onLaterPages=_add_watermark,
    )
