# src/saving/slides.py
import os
import re
import unicodedata
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable, Optional
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pydantic import BaseModel


def _get_items_from_result(result: Any) -> Iterable[Any]:
    """
    Try to extract a list of 'items' from any kind of result model.
    """
    if hasattr(result, "companies") and getattr(result, "companies", None):
        return result.companies

    if hasattr(result, "resources") and getattr(result, "resources", None):
        return result.resources

    if hasattr(result, "items") and getattr(result, "items", None):
        return result.items

    return []


def _save_result_slides(
    output_path: str | Path,
    layout: Any,
    flowchart_png_path: Optional[str] = None,
) -> None:
    """
    Create a PPTX from a DocumentLayout-like object and save to `output_path`.

    Expected layout fields:
      - layout.title: str
      - layout.slides: list of objects with .title and .bullets (list[str])

    If `flowchart_png_path` is provided and exists, a dedicated "Flowchart" slide
    will be inserted right after the title slide.
    """
    prs = Presentation()

    title_layout = prs.slide_layouts[0]   # title slide
    bullet_layout = prs.slide_layouts[1]  # title + content

    accent_blue = RGBColor(0x13, 0x3B, 0x5C)
    text_dark = RGBColor(0x33, 0x33, 0x33)
    subtitle_gray = RGBColor(0xDD, 0xDD, 0xDD)

    # ------------------------
    # Title slide
    # ------------------------
    first = layout.slides[0] if getattr(layout, "slides", None) else None
    slide = prs.slides.add_slide(title_layout)

    # Background color
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = accent_blue

    # 🔹 Main title: always the query / overall title
    title_text = (getattr(layout, "title", "") or "").strip() or "AI Research Result"

    title_shape = slide.shapes.title
    title_shape.text = title_text
    title_tf = title_shape.text_frame
    for p in title_tf.paragraphs:
        for run in p.runs:
            run.font.size = Pt(40)
            run.font.bold = True
            run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)  # white

    # 🔹 Subtitle: use first-slide title if it exists, fallback to tagline
    subtitle_text = (
        getattr(first, "title", "").strip()
        if first and getattr(first, "title", "").strip()
        else "Generated by AI Research Assistant"
    )

    if len(slide.placeholders) > 1:
        subtitle = slide.placeholders[1]
        subtitle.text = subtitle_text
        stf = subtitle.text_frame
        for p in stf.paragraphs:
            for run in p.runs:
                run.font.size = Pt(20)
                run.font.color.rgb = subtitle_gray

    # ------------------------
    # Optional Flowchart slide
    # ------------------------
    if flowchart_png_path:
        png_path = Path(flowchart_png_path)
        if png_path.exists():
            flow_slide = prs.slides.add_slide(bullet_layout)

            # Title
            flow_title_shape = flow_slide.shapes.title
            flow_title_shape.text = "Workflow / Architecture Overview"
            fttf = flow_title_shape.text_frame
            for p in fttf.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(24)
                    run.font.bold = True
                    run.font.color.rgb = accent_blue

            # Use content placeholder as a convenient anchor
            if len(flow_slide.placeholders) > 1:
                body = flow_slide.placeholders[1]
                # Position image reasonably within the placeholder box
                left = body.left
                top = body.top
                width = body.width
                height = body.height

                # You can constrain height/width if needed:
                # e.g. height = Inches(4.5)
                flow_slide.shapes.add_picture(str(png_path), left, top, width=width, height=height)

    # ------------------------
    # Content slides
    # ------------------------
    slides_data = getattr(layout, "slides", []) or []
    # We already used the first slide's title as subtitle, so start from the 2nd
    remaining_slides = slides_data[1:] if slides_data else []

    for slide_data in remaining_slides:
        slide = prs.slides.add_slide(bullet_layout)

        # Section title
        title_shape = slide.shapes.title
        title_shape.text = getattr(slide_data, "title", "") or ""
        ttf = title_shape.text_frame
        for p in ttf.paragraphs:
            for run in p.runs:
                run.font.size = Pt(28)
                run.font.bold = True
                run.font.color.rgb = accent_blue

        # Bullets
        body_shape = slide.placeholders[1]
        tf = body_shape.text_frame
        tf.clear()

        bullets = getattr(slide_data, "bullets", []) or []
        if bullets:
            for i, bullet in enumerate(bullets):
                p = tf.add_paragraph() if i > 0 else tf.paragraphs[0]
                p.text = bullet
                p.level = 0
                for run in p.runs:
                    run.font.size = Pt(18)
                    run.font.color.rgb = text_dark

    prs.save(str(output_path))
